services:
  invoice_management_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice_management_api
    restart: unless-stopped
    depends_on:
      - invoice_management_postgres
    ports:
      - '3333:3333'

  invoice_management_postgres:
    container_name: invoice_management_postgres
    image: postgres:13.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/invoice_management_postgres/data
